"""
Summary Generator Service
===========================
Generates the final doctor-ready structured clinical summary.
Combines: ACI conversation data + OCR documents + RAG past history.

Output format matches SIH26047 PS requirements:
  CC → HPI → Past Medical/Surgical → Medications → Allergies →
  Family → Personal → ROS → Investigations → Red Flags → When to Seek Help

Also generates patient-facing readback text in the conversation style.
"""

import logging
from typing import Any, Dict, List, Optional

from services.llm_client import llm_complete

logger = logging.getLogger(__name__)


# ── "When to Seek Immediate Help" templates (PS requirement) ──────────────────
# These are pre-validated, NOT generated by LLM

SEEK_HELP_TEMPLATES = {
    "chest_pain": [
        "Chest pain increasing in severity or not relieved by rest",
        "Sudden shortness of breath or difficulty breathing",
        "Pain spreading to jaw, neck, or both arms",
        "Sudden sweating, nausea, or feeling of impending doom",
        "Fainting or loss of consciousness",
        "→ Call 108 (Ambulance) or go to nearest Emergency Department immediately",
    ],
    "default": [
        "Symptoms worsening despite medication",
        "New symptoms appearing (fever, severe pain, bleeding)",
        "Difficulty breathing or chest tightness",
        "Sudden weakness on one side of body",
        "Loss of consciousness or seizures",
        "→ Visit your nearest hospital Emergency Department or call 108",
    ],
}


class SummaryGenerator:
    """Generates structured clinical summaries from collected data."""

    async def generate(
        self,
        patient_id: str,
        clinical_fields: Dict[str, str],
        red_flags: List[str],
        scanned_documents: List[Dict[str, Any]],
        past_history: Dict[str, Any],
    ) -> Dict[str, Any]:
        """
        Generate the complete structured clinical summary.

        In production, this would use an LLM to synthesize natural language.
        For prototype, we structure the collected fields directly.
        """
        # Determine chief complaint category for "when to seek help"
        cc = clinical_fields.get("chief_complaint", "").lower()
        if "chest" in cc or "heart" in cc or "seene" in cc or "chati" in cc:
            help_template = SEEK_HELP_TEMPLATES["chest_pain"]
        else:
            help_template = SEEK_HELP_TEMPLATES["default"]

        # Build HPI narrative from SOCRATES fields
        hpi = self._build_hpi(clinical_fields)

        # Compile medications from conversation + OCR + RAG
        current_meds = self._compile_medications(clinical_fields, scanned_documents, past_history)

        # Build chronological timeline
        timeline = self._build_timeline(scanned_documents, past_history, clinical_fields)

        # Compile lab values from scanned documents
        lab_values = []
        for doc in scanned_documents:
            for lab in doc.get("lab_values", []):
                lab_values.append(lab)

        # Generate AI clinical summary using LLM
        ai_summary = await self._synthesize_ai_summary(
            clinical_fields=clinical_fields,
            hpi=hpi,
            red_flags=red_flags,
            past_history=past_history,
        )

        # Text analysis → derived urgency signal for the doctor
        urgency = self._assess_urgency(clinical_fields, red_flags)

        # Build summary
        summary = {
            "patient_id": patient_id,
            "chief_complaint": clinical_fields.get("chief_complaint", "Not specified"),
            "hpi": hpi,
            "ai_summary": ai_summary,
            "urgency": urgency,
            "past_medical_history": self._get_past_medical(clinical_fields, past_history),
            "current_medications": current_meds,
            "allergies": self._get_allergies(clinical_fields),
            "family_history": self._get_family_history(clinical_fields),
            "personal_history": clinical_fields.get("personal_history", "Not assessed"),
            "review_of_systems": self._get_ros(clinical_fields),
            "investigations_summary": lab_values,
            "red_flags": red_flags,
            "when_to_seek_help": help_template,
            "rag_enriched": past_history.get("found", False),
            "past_visits": past_history.get("timeline", []),
            "timeline": timeline,
        }

        logger.info(
            "[SUMMARY] Generated for %s. RAG enriched: %s. Red flags: %d",
            patient_id,
            summary["rag_enriched"],
            len(red_flags),
        )

        return summary

    async def generate_readback(
        self,
        clinical_fields: Dict[str, str],
        style_mode: str,
        red_flags: List[str] = None,
    ) -> str:
        """
        Generate patient-facing readback text in the conversation style.
        PS Requirement: "patient-facing audio confirmation in local language".
        Data-driven: builds from the real collected fields. Falls back to a
        data-driven template if the LLM is unavailable.
        """
        red_flags = red_flags or []
        f = clinical_fields
        cc = f.get("chief_complaint", "your symptoms")
        onset = f.get("onset", "")
        character = f.get("character", "")
        severity = f.get("severity", "")
        meds = f.get("medications", "no regular medicines")
        allergies = f.get("allergies", "no allergies")
        associated = f.get("associated_symptoms", "")

        # Build a fuller data-driven readback using every collected field.
        detail = ""
        bits = []
        if onset:
            bits.append(f"shuru {onset}")
        if character:
            bits.append(f"type {character}")
        if severity:
            bits.append(f"severity {severity}")
        if associated and "no" not in associated.lower() and "none" not in associated.lower():
            bits.append(f"saath mein {associated}")
        if bits:
            detail = "; ".join(bits)

        if style_mode == "formal_hindi":
            s = [f"Namaste. Aapne bataya ki aapko {cc}."]
            if detail:
                s.append(f"Yeh {detail}.")
            s.append(f"Aap abhi {meds} le rahe hain. Aapko {allergies} ki allergy hai.")
            if red_flags:
                s.append("Kuch lakshanon ko dekh kar turant medical madad lena zaroori hai.")
            s.append("Kya yeh sab kuch sahi hai?")
            return " ".join(s)
        elif style_mode == "english_professional":
            s = [f"You reported {cc}."]
            if detail:
                s.append(f"Details: {detail}.")
            s.append(f"Your current medications include {meds}. You have allergies to {allergies}.")
            if red_flags:
                s.append("Some findings warrant prompt medical attention.")
            s.append("Is all of this information correct?")
            return " ".join(s)
        else:
            # Hinglish casual (default)
            s = [f"Aapne bataya ki aapko {cc}."]
            if detail:
                s.append(f"Details: {detail}.")
            s.append(f"Aap currently {meds} le rahe hain. Aapko {allergies} se allergy hai.")
            if red_flags:
                s.append("Kuch cheezein dekh kar jaldi se doctor ke paas jaana zaroori hai.")
            s.append("Kya yeh sab sahi hai?")
            return " ".join(s)

    # ── LLM Clinical Synthesis ─────────────────────────────────────────────

    _AI_SUMMARY_SYSTEM = (
        "You are an expert clinical scribe. "
        "Write a concise 2-3 sentence AI clinical summary for the attending doctor. "
        "Tone: professional, third-person, present-tense medical English. "
        "Include: chief complaint, key SOCRATES findings, relevant history, "
        "and any red flags. Do NOT suggest diagnoses. "
        "Max 80 words. Output plain text only — no bullet points, no headings."
    )

    async def _synthesize_ai_summary(
        self,
        clinical_fields: Dict[str, str],
        hpi: str,
        red_flags: List[str],
        past_history: Dict[str, Any],
    ) -> str:
        """
        Call LLM to synthesize a doctor-grade AI clinical summary.
        Falls back to a structured template if LLM unavailable.
        """
        chronic = past_history.get("chronic_conditions", [])
        past_meds = past_history.get("past_medications", [])

        prompt_parts = [
            f"Chief Complaint: {clinical_fields.get('chief_complaint', 'Not specified')}",
            f"HPI: {hpi}",
        ]
        if clinical_fields.get("past_medical"):
            prompt_parts.append(f"Past Medical History: {clinical_fields['past_medical']}")
        if chronic:
            prompt_parts.append(f"Known Chronic Conditions: {', '.join(chronic)}")
        if clinical_fields.get("medications"):
            prompt_parts.append(f"Current Medications: {clinical_fields['medications']}")
        if clinical_fields.get("allergies"):
            prompt_parts.append(f"Allergies: {clinical_fields['allergies']}")
        if red_flags:
            prompt_parts.append(f"Red Flags Detected: {'; '.join(red_flags)}")

        prompt = "Clinical data:\n" + "\n".join(prompt_parts) + "\n\nAI clinical summary:"

        result = await llm_complete(prompt, system=self._AI_SUMMARY_SYSTEM, max_tokens=120)
        result = result.strip()

        if not result or len(result) < 20:
            # Fallback template if LLM unavailable
            cc = clinical_fields.get("chief_complaint", "unspecified complaint")
            flag_note = (
                " Red flags noted — timely clinical review advised."
                if red_flags else
                " No acute red flags identified at intake."
            )
            result = (
                f"Patient presents with {cc}. "
                f"SOCRATES assessment completed via AI-assisted kiosk intake.{flag_note}"
            )

        logger.info("[SUMMARY] AI clinical summary generated (%d chars)", len(result))
        return result

    @staticmethod
    def _build_hpi(fields: Dict[str, str]) -> str:
        """Build HPI narrative from SOCRATES fields."""
        parts = []

        cc = fields.get("chief_complaint", "")
        if cc:
            parts.append(f"Patient presents with {cc}")

        onset = fields.get("onset", "")
        if onset:
            parts.append(f"onset {onset}")

        character = fields.get("character", "")
        if character:
            parts.append(f"described as {character} in nature")

        radiation = fields.get("radiation", "")
        if radiation and "no" not in radiation.lower():
            parts.append(f"radiating to {radiation}")

        exacerbating = fields.get("exacerbating", "")
        if exacerbating:
            parts.append(f"aggravated by {exacerbating}")

        severity = fields.get("severity", "")
        if severity:
            parts.append(f"severity rated {severity}")

        associated = fields.get("associated_symptoms", "")
        if associated and "none" not in associated.lower():
            parts.append(f"associated with {associated}")

        timing = fields.get("timing", "")
        if timing:
            parts.append(f"pattern: {timing}")

        return ". ".join(parts) + "." if parts else "No HPI data collected."

    @staticmethod
    def _compile_medications(
        fields: Dict[str, str],
        documents: List[Dict[str, Any]],
        past_history: Dict[str, Any],
    ) -> List[str]:
        """Compile unique medications from all sources."""
        raw_meds = []

        def _normalize(s: str) -> str:
            """Normalize dashes and whitespace for dedup."""
            import re
            s = s.replace("\u2014", " ").replace("\u2013", " ").replace("-", " ")
            s = re.sub(r'\s+', ' ', s).strip().lower()
            return s

        seen = set()

        def _add(med_str: str):
            key = _normalize(med_str)
            if key and key not in seen and "no " not in key:
                seen.add(key)
                raw_meds.append(med_str.strip())

        # From conversation
        patient_meds = fields.get("medications", "")
        if patient_meds:
            for m in patient_meds.replace(" and ", ",").replace(" aur ", ",").split(","):
                _add(m)

        # From scanned documents
        for doc in documents:
            for med in doc.get("medications", []):
                name = med.get("drug_name", "")
                strength = med.get("strength", "")
                freq = med.get("frequency", "")
                if name:
                    _add(f"{name} {strength} - {freq}")

        # From RAG past history
        for m in past_history.get("past_medications", []):
            _add(m)

        return sorted(raw_meds)

    @staticmethod
    def _get_past_medical(
        fields: Dict[str, str], past_history: Dict[str, Any]
    ) -> List[str]:
        """Get past medical history from conversation + RAG."""
        conditions = []

        pm = fields.get("past_medical", "")
        if pm and "none" not in pm.lower():
            conditions.append(pm)

        for c in past_history.get("chronic_conditions", []):
            if c not in conditions:
                conditions.append(c)

        return conditions if conditions else ["No significant past medical history reported"]

    @staticmethod
    def _get_allergies(fields: Dict[str, str]) -> List[str]:
        allergies = fields.get("allergies", "")
        if allergies and "no" not in allergies.lower() and "none" not in allergies.lower():
            return [allergies]
        return ["No known drug allergies (NKDA)"]

    @staticmethod
    def _get_family_history(fields: Dict[str, str]) -> List[str]:
        fh = fields.get("family_history", "")
        if fh and "no" not in fh.lower() and "none" not in fh.lower():
            return [fh]
        return ["No significant family history reported"]

    @staticmethod
    def _get_ros(fields: Dict[str, str]) -> str:
        associated = fields.get("associated_symptoms", "")
        if associated:
            return f"Positive for: {associated}. Remaining systems not assessed in kiosk intake."
        return "Not assessed in kiosk intake."

    @staticmethod
    def _assess_urgency(
        fields: Dict[str, str], red_flags: List[str]
    ) -> Dict[str, Any]:
        """
        Text analysis helper: derive a triage urgency level from the collected
        severity rating and any detected red flags. This is a deterministic
        rule (safety-critical → never free-form LLM), so it's simple and auditable.
        """
        max_severity = 0.0
        raw_sev = (fields.get("severity", "") or "").lower()
        # Extract a numeric severity like "7", "7/10", "8 out of 10".
        import re
        m = re.search(r"(\d{1,2})", raw_sev)
        if m:
            max_severity = min(10.0, float(m.group(1)))

        critical = any("[CRITICAL]" in f for f in red_flags)
        high = any("[HIGH]" in f for f in red_flags)
        count = len(red_flags)

        if critical:
            level = "CRITICAL"
        elif high or count >= 2:
            level = "HIGH"
        elif max_severity >= 7:
            level = "HIGH"
        elif max_severity >= 4:
            level = "MODERATE"
        else:
            level = "LOW"

        return {
            "level": level,
            "severity_score": max_severity,
            "red_flag_count": count,
            "note": (
                "Immediate clinical attention advised."
                if level in ("CRITICAL", "HIGH")
                else "Routine review within standard triage timeframe."
                if level == "MODERATE"
                else "No urgent findings at intake."
            ),
        }

    @staticmethod
    def _build_timeline(
        documents: List[Dict[str, Any]],
        past_history: Dict[str, Any],
        fields: Dict[str, str],
    ) -> List[Dict[str, Any]]:
        """Build chronological timeline from all sources."""
        timeline = []

        # Past visits from RAG
        for entry in past_history.get("timeline", []):
            timeline.append(entry)

        # Current visit
        from datetime import datetime
        timeline.append({
            "date": datetime.now().strftime("%Y-%m-%d"),
            "type": "current_visit",
            "doctor": "MediKiosk AI Intake",
            "summary": fields.get("chief_complaint", "Current visit"),
            "medications": [],
        })

        # Sort by date
        timeline.sort(key=lambda x: x.get("date", "9999"))

        return timeline
